name = "avery-label-studio"
pages_build_output_dir = "dist"
compatibility_date = "2026-07-05"
compatibility_flags = ["formdata_parser_supports_files"]

[vars]
JWT_SECRET = "local-secret-key-1234567890-qwertyuiop-super-long"

[[kv_namespaces]]
binding = "AUTO_LABELS_KV"
id = "499933a246354e9fb7ebe13b684ae7d3"

[[r2_buckets]]
binding = "AUTO_LABELS_R2"
bucket_name = "auto-labels-r2"
